server:
  port: 8090
spring:
  application:
    name: node-service
message: THIS IS SPRING BOOT VERSION 7
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    lease:
      duration: 5
  instance:
    prefer-ip-address: true