server:
  port: 9099

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    lease:
      duration: 5
  instance:
    prefer-ip-address: true
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password: sa
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

  cloud:
    config:
      uri: http://localhost:8888
      
logging:
  level:
    com.search.controller: FULL
    com.search.dao: DEBUG